# permissions for end users to view bgdeploys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bgdeploy-viewer-role
rules:
- apiGroups:
  - bgdeploy.swallowlab.com
  resources:
  - bgdeploys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bgdeploy.swallowlab.com
  resources:
  - bgdeploys/status
  verbs:
  - get
